### ISSUE TITLE
Write Proper Branch Name in Readme

### ISSUE THREAD

**Issue by somenath1435** [fossasia/open-event-android#1168] opened 2019-02-23 21:22 UTC
**Describe the chore**
The branch name written is 'dev' instead of 'development'.
Change the branch name in Readme.

**Would you like to work on the issue?**
- [x] Yes

**Comment by iamareebjamal** [comment] 2019-02-24 07:03
Duplicate of #1166

**Closed by iamareebjamal** 2019-02-24 07:03 UTC
