### ISSUE TITLE
Add default image when there is no image displayed in EventsFragment

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1207] opened 2019-03-01 10:23 UTC
**Describe the feature you'd like**
Add a default image when there is no image displayed in single event item in EventsFragment

**Screenshots**
<img src="https://i.ibb.co/YN75DLW/53160178-353134605286741-4791522226165776384-n.png" width="200">

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment] 2019-03-01 10:28
Duplicate of #1159

**Comment by anhanh11001** [comment] 2019-03-01 10:29
oh, so I will close this one

**Closed** 2019-03-01 10:29 UTC
