### ISSUE TITLE
Back button unresponsive for event screen in favorites section

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/open-event-android#685] opened 2018-11-03 17:07 UTC
**Describe the bug**
The back button and the on screen back arrow turn unresponsive for any event opened up from the favorites section .

**To Reproduce**
1. Go to the Likes tab  
2. Click on any event that you have Favorited
3. Try to press the back button or the back arrow in the top left corner.
4. Both seem to do nothing

**Expected behavior**
Back button should lead to the previous activity.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |OnePlus5|
|Android Version|Oreo 8.1|

**Would you like to work on the issue?**
YES

**Comment by iamareebjamal** [comment] 2018-11-03 17:40
This is most likely a duplicate of existing issue. The navigation is pretty much broken in the app

**Closed by iamareebjamal** 2018-11-03 17:40 UTC

**Comment by codepoet2017390** [comment] 2018-11-03 18:10
@iamareebjamal 
as stated by @trancenoid  the bug does not persist as per the latest merge to development branch. I was facing the issue because my local machine was behind the master. But now i have updated my local code and same Issue persists in Tickets section and i dont see a related issue open to it ? So what should be done?

**Comment by iamareebjamal** [comment] 2018-11-03 18:28
There are some PRs which have workarounds but no definitive fixes. You can see if you can fix the root bug because we don't want it to be fixed in one place and pop in another, which is happening currently
