### ISSUE TITLE
Menu icons disappearing, re-appear and disappear again

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1446] opened 2017-04-30 12:41 UTC
The menu icons have a strange behavior at times and disappear, sometimes re-appear and disappear again.

![screenshot_2017-04-30-14-39-34](https://cloud.githubusercontent.com/assets/1583873/25564414/221fa23e-2db3-11e7-8b05-407b3b889a79.png)

**Comment by iamareebjamal** [comment] 2017-05-05 07:12
@arp95 I think the issue is with 4.4 Kitkat, this should minimise the fixing time

**Comment by arp95** [comment] 2017-05-05 12:59
@iamareebjamal 
sure!
will look into this.

**Comment by arp95** [comment] 2017-05-05 15:18
referencing the stackoverflow link here: http://stackoverflow.com/questions/36445507/action-bar-icons-disappear-when-the-drawer-is-opened

main issue for this to happen is the invalidateOptionsMenu() being called in onDrawerOpened() and onDrawerClosed() functions. This should resolve the issue.

**Comment by free4murad** [comment] 2017-05-05 20:28
@arp95 @iamareebjamal 
Are you able to reproduce the bug? Its working fine on my device.

**Comment by iamareebjamal** [comment] 2017-05-05 20:30
Are you using Kitkat? 

It is working fine on 5.0+

**Comment by arp95** [comment] 2017-05-05 20:32
@free4murad actually i faced this error quite a while back. right now its working fine.
as @iamareebjamal pointed the reason has to be older versions.

**Comment by free4murad** [comment] 2017-05-05 20:32
using 
Android 4.3
Android 6.0

Working fine for me.

**Comment by arp95** [comment] 2017-05-05 20:34
found possible reasons for disappearence of menu icons, and i think its due the menu.clear() statement in onCreateOptionsMenu(). i think we have to use a inflator there for inflating the menu.

**Comment by free4murad** [comment] 2017-05-05 20:35
@mariobehling 
can you please confirm your device and android version?

**Comment by iamareebjamal** [comment] 2017-05-05 20:35
Nevertheless, the fix should be merged so it doesn't happen again. Bugs in support libraries are hard to reproduce and track as we don't know when and how they happen.

I'll try to look for more causes and until then you can add this fix in the PR as well @arp95 :+1: :smiley:

**Comment by harshitagupta30** [comment] 2017-05-05 20:35
It's working fine for me too.

**Comment by arp95** [comment] 2017-05-05 20:36
@free4murad @iamareebjamal 
do update me if you get this bug.
none the less sending the fix for this in the pr.

**Comment by free4murad** [comment] 2017-05-05 20:38
I am not debating if we should merge the fix or not. Merging a good option.

Just curious if anyone else is facing the same issue.

Also if we could get the development environment of the people experiencing the bug that wouls be great.

**Comment by arp95** [comment] 2017-05-05 20:48
@free4murad @iamareebjamal 
i think go through this link: http://stackoverflow.com/questions/19750635/icon-in-menu-not-showing-in-android

this is what we are looking for.

**Closed** 2017-05-06 17:36 UTC
Labels: bug
