### ISSUE TITLE
Add Sort By Filter

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1666] opened 2019-04-25 15:40 UTC
**Describe the feature you'd like**
Add Sort By Filters in Filter fragment with name, date, price, etc

**Would you like to work on the issue?**
- [x] Yes

**Comment by angmas1** [comment] 2019-04-25 18:44
Duplicate of #1645

**Comment by aggarwalpulkit596** [comment] 2019-04-25 18:47
@angmas1 I already have made a PR and it is been reviewed as well

**Comment by angmas1** [comment] 2019-04-25 18:48
Okay, no problem. Check before creating issue next time.

**Closed** 2019-04-28 17:15 UTC
