### ISSUE TITLE
App crashes on login/signup

### ISSUE THREAD

**Issue by aman210697** [fossasia/open-event-android#1251] opened 2019-03-09 13:01 UTC
**Describe the bug**
App is crashing login and signup

**Logs**
03-09 18:24:22.271 26551-26551/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 26551
    java.lang.NoSuchMethodError: No virtual method getAnnotationsByType(Ljava/lang/Class;)[Ljava/lang/annotation/Annotation; in class Ljava/lang/reflect/Method; or its super classes (declaration of 'java.lang.reflect.Method' appears in /system/framework/core-libart.jar)
        at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.isRequiredByAnnotation(KotlinAnnotationIntrospector.kt:61)
        at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.hasRequiredMarker(KotlinAnnotationIntrospector.kt:68)
        at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.access$hasRequiredMarker(KotlinAnnotationIntrospector.kt:23)
        at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector$hasRequiredMarker$1.invoke(KotlinAnnotationIntrospector.kt:33)
        at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector$hasRequiredMarker$1.invoke(KotlinAnnotationIntrospector.kt:23)
        at com.fasterxml.jackson.module.kotlin.ReflectionCache.javaMemberIsRequired(KotlinModule.kt:92)
        at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.hasRequiredMarker(KotlinAnnotationIntrospector.kt:26)
        at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.hasRequiredMarker(AnnotationIntrospectorPair.java:307)
        at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.hasRequiredMarker(AnnotationIntrospectorPair.java:307)
        at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder$4.withMember(POJOPropertyBuilder.java:655)
        at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder$4.withMember(POJOPropertyBuilder.java:652)
        at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.fromMemberAnnotations(POJOPropertyBuilder.java:1143)
        at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder._findRequired(POJOPropertyBuilder.java:652)
        at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getMetadata(POJOPropertyBuilder.java:220)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._constructWriter(BeanSerializerFactory.java:771)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:583)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:368)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:279)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:231)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:165)
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1388)
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1356)
        at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:551)
        at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:758)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.forRootType(ObjectWriter.java:1359)
        at com.fasterxml.jackson.databind.ObjectWriter.<init>(ObjectWriter.java:112)
        at com.fasterxml.jackson.databind.ObjectMapper._newWriter(ObjectMapper.java:689)
        at com.fasterxml.jackson.databind.ObjectMapper.writerFor(ObjectMapper.java:3351)
        at retrofit2.converter.jackson.JacksonConverterFactory.requestBodyConverter(JacksonConverterFactory.java:68)
        at retrofit2.Retrofit.nextRequestBodyConverter(Retrofit.java:280)
        at retrofit2.Retrofit.requestBodyConverter(Retrofit.java:260)
        at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:706)
        at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:295)
        at retrofit2.RequestFactory$Builder.build(RequestFactory.java:182)
        at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:65)
    	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:

**Smartphone Info:**

|Device : Samsung galaxy j7
|Android Version: Android 6.0.1

![20190309_181347](https://user-images.githubusercontent.com/24875315/54071909-58dfc400-4299-11e9-9bea-3fbb665e07ac.gif)

**Comment by iamareebjamal** [comment] 2019-03-09 13:02
Happening on development branch or play store deployed app?

**Comment by aman210697** [comment] 2019-03-09 13:21
> Happening on development branch or play store deployed app?

development branch

**Comment by iamareebjamal** [comment] 2019-03-10 06:47
@liveHarshit Is this issue reproducible on your end?

**Comment by liveHarshit** [comment] 2019-03-10 08:01
> @liveHarshit Is this issue reproducible on your end?

Yes. Also crashing while switching between login and sign up fragment. This issue is due to Safe Args. @haroldadmin Can you please analyze the bug?

**Comment by haroldadmin** [comment] 2019-03-10 08:02
@liveHarshit @iamareebjamal It's gonna take me some time to submit a PR to fix this. Mid sem exams this week.

If it's a really urgent issue, you can assign it to someone else too.

**Comment by liveHarshit** [comment] 2019-03-10 08:19
It's okay. Also, I'm not asking to submit the PR. 
@aman210697 Would you like to work on this issue?

**Comment by haroldadmin** [comment] 2019-03-10 08:30
@liveHarshit I have done some prelim analysis in #1242 

Also, I'm not able to reproduce this issue on my phone. I can login just fine.

**Comment by aman210697** [comment] 2019-03-10 12:07
> It's okay. Also, I'm not asking to submit the PR.
> @aman210697 Would you like to work on this issue?

I am sure I can fix it.
And it is crashing in samsung only

**Comment by liveHarshit** [comment] 2019-03-10 12:19
> > It's okay. Also, I'm not asking to submit the PR.
> > @aman210697 Would you like to work on this issue?
> 
> I am sure I can fix it.
> And it is crashing in samsung only

Really. I have also tested on Samsung this time.
Please go ahead.

**Comment by aman210697** [comment] 2019-03-10 12:32
> > > It's okay. Also, I'm not asking to submit the PR.
> > > @aman210697 Would you like to work on this issue?
> > 
> > 
> > I am sure I can fix it.
> > And it is crashing in samsung only
> 
> Really. I have also tested on Samsung this time.
> Please go ahead.

sorry, check my edited reply

**Comment by liveHarshit** [comment] 2019-03-10 12:36
Okay I will see.

**Comment by theLimitBreaker** [comment] 2019-04-24 05:01
@aman210697  does issue still exists on Samsung Devices ?

**Closed** 2019-05-19 06:10 UTC
