### ISSUE TITLE
"Network not available" Dialog created twice

### ISSUE THREAD

**Issue by jodiwaljay** [fossasia/open-event-android#1150] opened 2017-02-22 09:06 UTC
**Actual Behaviour**
 "Network not available" dialog appears twice.

**Expected Behaviour**
The dialog should appear only once.

**Steps to reproduce it**
You open the app as usual, with internet. Let it download the latest schedule. Now turn off the internet and you will see a "Network not available" dialog. If you dispose it, there will be another one.
Attached is screen recorded issue.
[Screen Recording.zip](https://github.com/fossasia/open-event-android/files/792768/Screen.Recording.zip)

**LogCat for the issue**

![img_20170222_142227](https://cloud.githubusercontent.com/assets/17160296/23204200/9ee76068-f90b-11e6-903e-4ccb71ae660f.jpg)

**Screenshots of the issue**

**Would you like to work on the issue?**
The Broadcast receiver for network connectivity change is itself receiving the information twice. The issue lies in there itself. Somehow, this network connectivity change is triggered twice.
I am currently working on it. Any help would be appreciated.

P.S.: I am contributing to this project for the first time, or any open source project for that matter. Though I have good experience in Android app dev but if anything appears out of context, please enlighten me with the details about proceeding further.

**Comment by harshitagupta30** [comment] 2017-02-22 12:22
Hi, @jodiwaljay! Thanks, for reporting but I couldn't reproduce the bug. You can see the screenshot of the log.

![screenshot from 2017-02-22 17 45 38](https://cloud.githubusercontent.com/assets/12701036/23211249/2a6f3b90-f927-11e6-9443-e0c24d47360d.png)

@the-dagger @free4murad Can you guys also check and verify it? :+1:

**Comment by jodiwaljay** [comment] 2017-02-22 13:19
Hello @harshitagupta30 ! While opening the app, was it connected to the internet. Also can you please check it for API 22.

**Comment by jodiwaljay** [comment] 2017-02-24 07:03
@harshitagupta30 @the-dagger I tested on emulator for API 22 and 23. I found out that issue does not persists for API 23, but exists for API 22. So perhaps the problem was in one of the android library which is rectified in future versions. Tell me if I should close the issue or not. Also thanks to @harshitagupta30 for notifying about it.

**Comment by the-dagger** [comment] 2017-02-25 10:22
@jodiwaljay I think that we can close this issue as of now.
Since this is not only fixed in the latest version but this isn't a deal breaker anyways even on lower APIs.

Thanks for opening this, appreciate it 🙂

**Closed by the-dagger** 2017-02-25 10:22 UTC
