### ISSUE TITLE
The share and the map button auto disappears in the sessiondetail activity

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#1627] opened 2017-05-31 20:32 UTC
**Actual Behaviour**

The share and the map button auto disappears in the session details activity

**Expected Behaviour**

They should be there as expected.

**Steps to reproduce it**

1. Open a session from the schedule fragment.
2. Click on the map icon on the action bar.
3. Press the back button to return to the session details.

**Screenshots of the issue**

![screenshot_2017-06-01-01-51-08-273_org fossasia openevent](https://cloud.githubusercontent.com/assets/13241256/26652635/284d4566-466e-11e7-8325-80c7258cc52b.png)
![screenshot_2017-06-01-01-51-31-846_org fossasia openevent](https://cloud.githubusercontent.com/assets/13241256/26652636/284f3dbc-466e-11e7-854a-bbc24dc46169.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 4](https://github.com/fossasia/open-event-android/milestone/27)

**Comment by iamareebjamal** [comment] 2017-06-01 01:49
@rohanagarwal94 This is a duplicate of #1551 

Please work on that if you can solve it.

**Closed** 2017-06-01 17:05 UTC
