### ISSUE TITLE
App stopped after clicking on the image of events to see the info in it.

### ISSUE THREAD

**Issue by cckole** [fossasia/open-event-android#1772] opened 2019-05-16 10:10 UTC
**Describe the bug**
After I input singapore as the location I wanted to check, I clicked on one of the pictures and it took me to another page. while on that page, the app crashed. It was a sudden close.

**To Reproduce**

- launch the app
- Click on pick a city
- Enter a location. SINGAPORE for example
- Click on any picture
- Wait a little and note as the app closes

**Expected behavior**
My expectation was to stay on the page, read all the info, and leave at my convinience time.

**Logs**
I will add log soon

**Screenshots**
https://youtu.be/OSVrj0gdBFs

**Smartphone Info:**

Device     [Tecno spark k7] 
Android Version [7.0] 

**Additional context**
This happens whether you are logged in or not. Sometimes, clicking on the picture might not respond before it crashes. The behavoior is not straight forward. If you are unable to reproduce on a first try, use it consistently, you will notice this in no time.

**Would you like to work on the issue?**
You can assign it to another dev. Still reporting more.

**Comment by liveHarshit** [comment] 2019-05-16 10:23
Can you please provide logs. It should due to memory leak. Issue #1795

**Comment by cckole** [comment] 2019-05-17 14:55
### Let's see if this help.

```05-15 18:32:53.477 14706 14767 E AndroidRuntime: FATAL EXCEPTION: arch_disk_io_0
05-15 18:32:53.477 14706 14767 E AndroidRuntime: Process: com.eventyay.attendee, PID: 14706
05-15 18:32:53.477 14706 14767 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 130060 byte allocation with 6272 free bytes and 6KB until OOM
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at java.util.Arrays.copyOf(Arrays.java:3256)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at sun.misc.IOUtils.readFully(IOUtils.java:60)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at java.util.jar.JarFile.getBytes(JarFile.java:395)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at java.util.jar.JarFile.getManifestFromReference(JarFile.java:187)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at java.util.jar.JarFile.getInputStream(JarFile.java:431)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:162)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at java.net.URL.openStream(URL.java:1057)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:979)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsResourceLoader.loadResource(BuiltInsResourceLoader.kt:12)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl$createPackageFragmentProvider$1.invoke(BuiltInsLoaderImpl.kt:40)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl$createPackageFragmentProvider$1.invoke(BuiltInsLoaderImpl.kt:23)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl.createBuiltInPackageFragmentProvider(BuiltInsLoaderImpl.kt:55)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl.createPackageFragmentProvider(BuiltInsLoaderImpl.kt:33)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:127)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(JvmBuiltIns.kt:43)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(JvmBuiltIns.kt:18)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:58)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:37)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:34)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(KDeclarationContainerImpl.kt)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:47)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:44)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:179)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KClassImpl.getConstructorDescriptors(KClassImpl.kt:196)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:91)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:44)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KClassImpl$Data.getConstructors(KClassImpl.kt)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.internal.KClassImpl.getConstructors(KClassImpl.kt:235)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at kotlin.reflect.jvm.ReflectJvmMapping.getKotlinFunction(ReflectJvmMapping.kt:149)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.module.kotlin.KotlinNamesAnnotationIntrospector.findKotlinParameterName(KotlinModule.kt:180)
05-15 18:32:53.477 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.module.kotlin.KotlinNamesAnnotationIntrospector.findImplicitPropertyName(KotlinModule.kt:106)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findImplicitPropertyName(AnnotationIntrospectorPair.java:490)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreatorParam(POJOPropertiesCollector.java:485)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreators(POJOPropertiesCollector.java:465)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:313)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:287)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:170)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:349)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:333)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:257)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:214)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:137)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4190)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3979)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2758)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.github.jasminb.jsonapi.ResourceConverter.readObject(ResourceConverter.java:333)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.github.jasminb.jsonapi.ResourceConverter.readDocumentCollection(ResourceConverter.java:276)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.github.jasminb.jsonapi.retrofit.JSONAPIResponseBodyConverter.convert(JSONAPIResponseBodyConverter.java:35)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at com.github.jasminb.jsonapi.retrofit.JSONAPIResponseBodyConverter.convert(JSONAPIResponseBodyConverter.java:15)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at c.l.a(OkHttpCall.java:223)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at c.l.a(OkHttpCall.java:186)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at c.a.a.c.b(CallExecuteObservable.java:42)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.m.a(Observable.java:12267)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at c.a.a.a.b(BodyObservable.java:34)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.m.a(Observable.java:12267)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.e.b.h.b(FlowableFromObservable.java:29)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.f.a(Flowable.java:14827)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.e.b.o.b(FlowableOnBackpressureLatest.java:32)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.f.a(Flowable.java:14827)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.e.b.j.b(FlowableMap.java:37)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.f.a(Flowable.java:14827)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.e.b.f.b(FlowableFlatMap.java:53)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.f.a(Flowable.java:14827)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.f.a(Flowable.java:14774)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.e.b.r$b.c(FlowableSwitchMap.java:129)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.e.b.g$a.a(FlowableFlatMapMaybe.java:175)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.e.b.g$a$a.a(FlowableFlatMapMaybe.java:397)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.e.c.a.b(MaybeFromCallable.java:61)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.j.a(Maybe.java:4290)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.e.b.g$a.c(FlowableFlatMapMaybe.java:132)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.e.b.k$c.h(FlowableObserveOn.java:407)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.e.b.k$a.run(FlowableObserveOn.java:176)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.g.d$c$a.run(ExecutorScheduler.java:288)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at a.a.e.g.d$c.run(ExecutorScheduler.java:253)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-15 18:32:53.622 14706 14767 E AndroidRuntime: at java.lang.Thread.run(Thread.java:761)```

**Comment by anhanh11001** [comment] 2019-05-17 16:18
Can you update your branch to the latest commits, I think this issue is fixed now.

**Comment by liveHarshit** [comment] 2019-05-17 16:19
Yes I was right it is duplicate of #1705

**Comment by liveHarshit** [comment] 2019-05-17 16:20
> Can you update your branch to the latest commits, I think this issue is fixed now.

But PR is not merged. #1766

**Comment by anhanh11001** [comment] 2019-05-17 16:27
Not that one. I deleted the use of Koin Scope in #1770  when I upgrade the Koin version, and it does help making the app not crash. I still keep #1766 as Leak Canary still report leaks not only in EventsFragment and most of other fragments that require setting up RecyclerView with adapter (I'll open a new issue now)

**Comment by liveHarshit** [comment] 2019-05-17 16:35
Yes, Most of the detected leaks are related to recycle view adapter.

**Comment by liveHarshit** [comment] 2019-05-17 16:37
Also there are several leaks related to coordinator layout, swipe refresh layout and bitmap.

**Closed** 2019-06-16 04:32 UTC
Labels: feature
