### ISSUE TITLE
Fix back button functionality in Attendees Fragment

### ISSUE THREAD

**Issue by Hariram-R** [fossasia/open-event-android#780] opened 2018-12-27 14:09 UTC
**Describe the bug**
Tapping on the back button while in the Attendee Details Fragment only causes the title in the app bar to change to 'Events' and further tapping the button causes the app to exit.
**To Reproduce**
1. Go to 'Attendee Detalils Fragment' - by choosing to purchase ticket to any event.
2. Press the back button - app bar changes to 'Events'
3. Press back button again - app closes.

**Expected behavior**
Press the back button in AttendeesFragment - dialog box requesting confirmation of ticket purchase cancellation. On confirmation, Events fragment loads.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung Galaxy J7 Max|
|Android Version|7.0 |

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment] 2018-12-27 14:21
Duplicate of #726

**Comment by Hariram-R** [comment] 2018-12-27 15:04
> 
> 
> Duplicate of #726

The issue seems to be present in both fragments - #726 solves only Ticket details fragment. Thoughts?

**Comment by liveHarshit** [comment] 2018-12-27 15:22
No, it's same because both fragments are set on root layout of Main Activity. And on frame container, Event fragment is set. App exit due to `is EventsFragment -> finish()`, which is placed inside back pressed method on Main activity.
```java
val rootFragment = this.supportFragmentManager.findFragmentById(R.id.rootLayout)
        if (rootFragment is EventDetailsFragment)
            super.onBackPressed()
```
The solution is to handle both fragments with rootFragment.

**Closed** 2019-01-03 17:42 UTC
