### ISSUE TITLE
Positioning of Circular Progress Bar in the Sign Up Screen

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#661] opened 2018-10-26 18:00 UTC
**Describe the feature you'd like**

On clicking the sign-up button the circular progress bar appears on the top left corner but for better UX it should replace the text inside Sign up button.
**Screenshots**

![progress_bar](https://user-images.githubusercontent.com/34534870/47584107-e5d35200-d976-11e8-8ac7-d72901a94c5e.jpg)

**Additional context**

Your views on this @iamareebjamal.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment] 2018-10-26 19:12
Duplicate of #647

**Closed by iamareebjamal** 2018-10-26 19:12 UTC
