### ISSUE TITLE
Provide Valid Location Options when changing Location

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1278] opened 2019-03-12 12:37 UTC
**Describe the bug**
When changing the Location, Uses can type anything in location . And this is not validated.

**To Reproduce**

**Expected behavior**
User should be presented with list of Location names while she/he is typing .
An autocomplete list of places

**Logs**

**Screenshots**

<img src="https://user-images.githubusercontent.com/24780524/54200533-a0608d00-44f1-11e9-9b14-4d2538b3dce2.gif" width=360>

**Smartphone Info:**

Device        : Nokia 6.1
Android Version: Android 9.0 PIE
**Additional context**

**Would you like to work on the issue?**

- [ :heavy_check_mark:   ] Yes
- [ ] No

**Comment by anhanh11001** [comment] 2019-03-12 16:14
I think this is the duplicate of #799

**Comment by theLimitBreaker** [comment] 2019-03-12 16:26
Ok This One Is duplicate too . Closing this . But No work has been done . Could I take this ?

**Closed** 2019-03-13 16:29 UTC
