### ISSUE TITLE
Options to send a message to organizer

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1388] opened 2019-03-24 11:48 UTC
**Describe the feature you'd like**
Create a fragment to send a message to the organizer in the EventFragment and TicketDetailsFragment.

**Screenshots**
Current status of the EventFragment
<img src="https://i.ibb.co/b7R27GV/55516218-336540823734538-7956929203675332608-n.png" width="300"/>

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment] 2019-03-24 11:54
And how will the message be sent?

**Comment by anhanh11001** [comment] 2019-03-24 14:06
@iamareebjamal My solution is to use JavaMail API for Android in here and build the process of sending messages from there. Here are some of the references I'm looking at: 
https://medium.com/@ssaurel/how-to-send-an-email-with-javamail-api-in-android-2fc405441079
https://stackoverflow.com/a/25136400

So the only problem I'm thinking of is that in the Authentication process, it must provide the email and password from the sender: So I think probably the email's name of the user will be moved in the body of the message, and the sender will be an email account created ourselves because of course, we don't know the password of user's email. So I'm not sure storing password inside the codebase is a good thing or how to do it properly for now.

But what's your thoughts on this issue and the one similar to that #1386 ealier?

**Comment by angmas1** [comment] 2019-03-24 15:18
Duplicate of #158

**Comment by iamareebjamal** [comment] 2019-03-24 16:52
Not good. We don't want to be a Mailing App

**Closed by iamareebjamal** 2019-03-24 16:52 UTC
