### ISSUE TITLE
Wrong toolbar title on Likes fragment after going back from event details

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-android#740] opened 2018-12-16 12:26 UTC
**Describe the bug**

After going back from event details to the Likes fragment, the toolbar title is 'Events'.

**To Reproduce**

1. Go to Likes.
2. Click on any event.
3. Press back button.
4. Toolbar title is 'Events'.

**Expected behaviour**

Toolbar title should have been 'Likes'.

**GIF**

![ezgif com-video-to-gif 6](https://user-images.githubusercontent.com/35566748/50053467-aeee1100-015b-11e9-9556-d9a7ec11a54b.gif)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by pranavpandey1998official** [comment] 2018-12-17 08:39
#736 these two are same issue

**Comment by liveHarshit** [comment] 2018-12-17 09:00
> #736 these two are same issue

Yes, problem is withEventDeatailFragment while returning from the fragment.

**Comment by iamareebjamal** [comment] 2018-12-17 13:33
Duplicate of #736

**Closed by iamareebjamal** 2018-12-17 13:33 UTC
