### ISSUE TITLE
App Crash on LoginFragment

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1279] opened 2019-03-12 12:52 UTC
**Describe the bug**
When Not logged in , on switching from signup to login fragment App crashes

**To Reproduce**
Provided You are not logged in
1. Go to 'Profile Tab'
2. Click on 'sign up tab'
3. Click on 'login tab'
4. App Crashes

**Expected behavior**
App should not crash

**Logs**
```
2019-03-12 18:36:12.326 10885-10885/com.eventyay.attendee E/SmartAuthViewModel: 2 -1
2019-03-12 18:36:16.262 10885-10885/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 10885
    java.lang.IllegalStateException: Fragment LoginFragment{949073 (d717441d-ff15-4ca1-8655-00fe826da6e2) id=0x7f0800f7} has null arguments
        at org.fossasia.openevent.general.auth.LoginFragment$$special$$inlined$navArgs$1.invoke(FragmentNavArgsLazy.kt:42)
        at org.fossasia.openevent.general.auth.LoginFragment$$special$$inlined$navArgs$1.invoke(Unknown Source:0)
        at androidx.navigation.NavArgsLazy.getValue(NavArgsLazy.kt:44)
        at androidx.navigation.NavArgsLazy.getValue(NavArgsLazy.kt:34)
        at org.fossasia.openevent.general.auth.LoginFragment.getSafeArgs(Unknown Source:28)
        at org.fossasia.openevent.general.auth.LoginFragment.showSnackbar(LoginFragment.kt:214)
        at org.fossasia.openevent.general.auth.LoginFragment.onCreateView(LoginFragment.kt:60)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2530)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:887)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2090)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1864)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1820)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1721)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:147)
        at android.os.Handler.handleCallback(Handler.java:898)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6716)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Screenshots**
<img src="https://user-images.githubusercontent.com/24780524/54201394-87f17200-44f3-11e9-8b9c-bdfbe59b63f1.gif" width=360>

**Smartphone Info:**

Device  : Nokia 6.1
Android Version : Android 9.0 pie

**Would you like to work on the issue?**

- [ :heavy_check_mark:   ] Yes
- [ ] No

**Comment by addiegupta** [comment] 2019-03-12 13:25
I think this is already covered in Issue #1242

**Comment by ShridharGoel** [comment] 2019-03-12 13:25
Duplicate of #1242

**Comment by theLimitBreaker** [comment] 2019-03-12 13:40
Ok Its duplicate !. But I see No work is done till Now . Could I work on it after closing this. And then would reference original one

**Comment by ShridharGoel** [comment] 2019-03-12 13:45
@haroldadmin had said that he would be working on that issue. You can comment there and ask him.

**Comment by theLimitBreaker** [comment] 2019-03-12 13:46
ok thank you

**Closed** 2019-03-12 13:47 UTC
