### ISSUE TITLE
Crash when updating app due to database migration

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1268] opened 2017-03-08 16:07 UTC
**Actual Behaviour**

Clicking on any event leads to 
`android.database.sqlite.SQLiteException: no such column: shortBiography (code 1): , while compiling: SELECT id, name, photo, shortBiography, email, web, facebook, twitter, github, linkedin, organisation, position, country FROM speakers WHERE id == 1`

I think this occurs due to a recent db schema change? I'm not sure, but it should be handled gracefully.

**Expected Behaviour**

Clicking on any event should open its details. Doesn't matter if the app was updated

**Steps to reproduce it**

1. Update app from old codebase
2. Click on any event
3. App crashes on invocation of `org.fossasia.openevent.dbutils.DatabaseOperations.getSpeakersbySessionName(DatabaseOperations.java:857)`

**LogCat for the issue**

```
Process: org.fossasia.openevent, PID: 4381
                                                                      android.database.sqlite.SQLiteException: no such column: shortBiography (code 1): , while compiling: SELECT id, name, photo, shortBiography, email, web, facebook, twitter, github, linkedin, organisation, position, country FROM speakers WHERE id == 1
                                                                          at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                          at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                          at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                          at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                          at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                          at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                          at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                          at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                          at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                                                                          at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                                                                          at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1202)
                                                                          at org.fossasia.openevent.dbutils.DatabaseOperations.getSpeakersbySessionName(DatabaseOperations.java:857)
                                                                          at org.fossasia.openevent.dbutils.DbSingleton.getSpeakersbySessionName(DbSingleton.java:150)
                                                                          at org.fossasia.openevent.adapters.SessionsListAdapter.onBindViewHolder(SessionsListAdapter.java:154)
                                                                          at org.fossasia.openevent.adapters.SessionsListAdapter.onBindViewHolder(SessionsListAdapter.java:56)
```

**Would you like to work on the issue?**

I unfortunately reinstalled the app and can't reproduce the bug without digging much into old commits, so no

**Comment by mananwason** [comment] 2017-03-10 18:49
I'm also not able to reproduce this, so let's close it for now

**Closed by mananwason** 2017-03-10 18:49 UTC
