### ISSUE TITLE
Speaker's thumbnail and sponsors's image are not displaying when app is offline.

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1421] opened 2017-04-17 09:46 UTC
**Actual Behaviour**

Speaker's thumbnail and sponsors's image are not displaying when app is offline. Speaker's thumbnail and sponsors's image are getting reloaded  when user reopens app after closing. It sends request to server for thumbnails each time, so more data is being used. So when there is no internet it is not displaying thumbnails and images.

**Expected Behaviour**

Display speaker's thumbnails and sponsor's images even if there is no internet by providing more cache.

**Steps to reproduce it**

Turn off internet connection and go to SpeakersFragment and SponsorsFragment.

**Screenshots of the issue**
Note: There is no internet connection

![before_speaker](https://cloud.githubusercontent.com/assets/18264684/25085543/75c1ff14-2380-11e7-9b14-886ef81c2c07.png)

![before_sponser](https://cloud.githubusercontent.com/assets/18264684/25085550/7fa8bdf6-2380-11e7-9c4c-e5efd07bf9f5.png)

**Would you like to work on the issue?**

Yes, i would like to work on this.

**Comment by the-dagger** [comment] 2017-05-02 18:40
Duplicate of #1326 
@Shailesh351 Please work with @arp95 on your existing implementation.

**Closed by the-dagger** 2017-05-02 18:40 UTC
Labels: bug
