### ISSUE TITLE
Inapproprite order shimmer placeholder

### ISSUE THREAD

**Issue by aman210697** [fossasia/open-event-android#1424] opened 2019-03-25 18:47 UTC
**Describe the bug**
place holder views are of fixed size

**Smartphone Info:**

|Device         |Redmi note 3|
|Android Version| Pie with smaller dpi  |
 
**Screenshot**

![WhatsApp Image 2019-03-26 at 12 04 19 AM](https://user-images.githubusercontent.com/24875315/54945690-6d3fe400-4f5c-11e9-81a9-f7d14faa2047.jpeg)

**Would you like to work on the issue?**
-  Yes

**Comment by somenath1435** [comment] 2019-03-26 00:28
@aman210697 This issue is duplicate of #1419.
I'm already working on it.
Please check open issues before opening a new one.

**Closed** 2019-04-04 07:31 UTC
