### ISSUE TITLE
UI overlapping with no result found and Location text.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#679] opened 2018-11-02 09:57 UTC
**Describe the bug**

Overlapping takes place when no search results are found with the location text.

**To Reproduce**

1. Go to the search fragment.
2. Do a random search with no results.
3. Change tabs and then come back to the search tab.

**Expected behavior**

Space between the view and if needed a division to display previous results.

**Screenshots**

![results](https://user-images.githubusercontent.com/34534870/47908682-b7dc9900-deb3-11e8-8a6f-8ae5d21e09d0.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version| Oreo 8.1.0   |

**Would you like to work on the issue?**

 Yes

Your reviews @iamareebjamal

**Comment by liveHarshit** [comment] 2018-11-02 10:36
@kshitijsuri90 Duplicate of #644 Has PR #651

**Comment by iamareebjamal** [comment] 2018-11-02 12:12
Duplicate of #644

**Closed by iamareebjamal** 2018-11-02 12:12 UTC
