### ISSUE TITLE
Add sharing ticket feature

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1699] opened 2019-04-30 08:50 UTC
**Describe the feature you'd like**
A screenshot bitmap of ticket that can be shared to other apps

**Would you like to work on the issue?**
Yes

**Comment by theLimitBreaker** [comment] 2019-04-30 08:54
Duplicate of #1353

**Comment by anhanh11001** [comment] 2019-04-30 09:34
@theLimitBreaker oh I didn't notice, are you still working on this because I'm nearly finished?

**Comment by theLimitBreaker** [comment] 2019-04-30 09:44
Umm it's been inactive for quite awhile . It's was on low priority. Also been busy with exams 
If you are nearly finished. You could make the PR

**Closed** 2019-04-30 10:47 UTC
