### ISSUE TITLE
Back Key in the title bar is not functioning  

### ISSUE THREAD

**Issue by RebelsterPi** [fossasia/open-event-android#925] opened 2019-01-19 15:03 UTC
**Describe the bug**

Back Key in the title bar of searchLocationFragment 

**To Reproduce**

1. Open the application   
2. Select "Where"  in the Events fragments or Search Fragment.
3. try going back using the back button in the title bar.
           
**Expected behavior**

Supposed to go back to the previous fragment from the search location fragment.

**Screenshots**

![screenshot_2019-01-19-20-26-41](https://user-images.githubusercontent.com/37181637/51428413-58c43000-1c29-11e9-932f-2ef71e2c7f7e.png)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment] 2019-01-19 15:07
Duplicate of #922

**Comment by yashk2000** [comment] 2019-01-19 15:13
@RebelsterPi this is same as #922 on which I am already working

**Comment by RebelsterPi** [comment] 2019-01-19 15:17
Ok then. Go ahead!

**Comment by liveHarshit** [comment] 2019-01-19 15:32
Duplicate of #922

**Closed** 2019-01-19 15:32 UTC
