### ISSUE TITLE
App keeps toggling between Events and Profile fragment

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-android#716] opened 2018-12-08 10:38 UTC
**Describe the bug**
After going back from Profile fragment to Events, if we press back button again then Profile fragment opens up (although on the navigation bar, 'Events' remains selected) and on again pressing back, it goes to Events. This process can be done again and again.

**To Reproduce**
1. Go to Profile.
2. Click on back button.
3. Events will open.
4. Again go back.
5. Now, profile will open.
6. Again go back.
7. Again events will open.
8. This will continue.

**Expected behavior**
On pressing back from the Events screen, app should close.

**GIF**
![ezgif com-video-to-gif 11](https://user-images.githubusercontent.com/35566748/49685538-ca796c00-fb0a-11e8-8abc-51ce4f8a7b46.gif)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by liveHarshit** [comment] 2018-12-08 13:18
Issue #626 is same.

**Comment by iamareebjamal** [comment] 2018-12-08 13:20
Duplicate of #626

**Closed by iamareebjamal** 2018-12-08 13:20 UTC
