### ISSUE TITLE
Data Loss on Rotating Screen 

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1191] opened 2019-02-27 11:06 UTC
**Describe the bug**
In TicketsFragment, changes on Spinner is not retained when rotating

**Screenshots**
Before rotating:
<img src="https://i.ibb.co/k3ywRmb/52935412-2078389328921258-6291597484812664832-n.png" width="200">

After rotating:
<img src="https://i.ibb.co/fqPdQhH/53066223-2292829690963042-5918015873582366720-n.png" height="200">

**Would you like to work on the issue?**
No

**Comment by angmas1** [comment] 2019-02-28 09:36
I would like to work on this.

**Comment by anhanh11001** [comment] 2019-02-28 11:38
Please go ahead

**Comment by tavishjain** [comment] 2019-03-03 16:49
Has this issue been resolved ?

**Comment by anhanh11001** [comment] 2019-03-03 17:33
@tavishjain I don't think so...

**Comment by tavishjain** [comment] 2019-03-03 18:26
Ok then. May I work upon this ?

**Comment by anhanh11001** [comment] 2019-03-03 18:42
Of course

**Comment by pranavpandey1998official** [comment] 2019-03-04 18:41
duplicate of #967

**Comment by anhanh11001** [comment] 2019-03-10 20:29
@pranavpandey1998official this one is on TicketsFragment, #967 is on AttendeeFragment, it is two different issue. Please take a look again.
@iamareebjamal can you open this issue again?

**Comment by pranavpandey1998official** [comment] 2019-03-10 20:36
#1097 sorry i reference the wrong one

**Comment by theLimitBreaker** [comment] 2019-03-12 12:06
Hello I would like to work on this issue! It seems still not resolved and No one is working on it

**Closed** 2019-04-10 20:22 UTC
