### ISSUE TITLE
FavoriteEventsRecyclerView becomes empty on returning to its fragment

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1325] opened 2019-03-16 13:24 UTC
**Describe the bug**

The FavoriteEventsRecyclerView shows its empty view on returning to its view after returning from viewing a favorite event.

**To Reproduce**
 The RecyclerView displays the empty view

**Expected behavior**

The favorite events should be displayed

**Logs**

**Screenshots**

![Issue 1325](https://user-images.githubusercontent.com/22665789/54475936-6bb84280-481d-11e9-9ad3-d2a3320ad629.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 6.1 Plus|
|Android Version| Pie 9.0   |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by haroldadmin** [comment] 2019-03-16 19:44
Could be possibly related to #1294 because it uses a global variable to keep of whether the list has been fetched or not. The problem is compounded by the fact that that our fragments use the fragment lifecycle to observe live data instead of their `viewLifecycleOwner` to observe live data.

I can confirm that this issue is not present on #1240

**Comment by haroldadmin** [comment] 2019-03-22 03:17
@iamareebjamal @liveHarshit As far as I can tell, this issue has been fixed with #1240 
Please verify it if you can and close this issue.

**Closed** 2019-03-22 08:30 UTC
