### ISSUE TITLE
Add Pagination to Home Fragment

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1678] opened 2019-04-27 13:42 UTC
**Describe the feature you'd like**
Add Pagination to Events Fragment to show more results currently it shows only the top 20 results and there's no way to load other results.A similar implementation can be applied to the searchresultsfragment 

**Would you like to work on the issue?**
- [x] Yes

**Comment by theLimitBreaker** [comment] 2019-04-27 14:13
Duplicate of #84  Please ask prior issue opener . or mentors before working on this

**Closed** 2019-04-27 15:54 UTC
